import subprocess
import time
import os

BASE_PATH = os.path.expanduser("~/Smart-Home-Escape-Room-Workshop/Python/Laptop/")

if __name__ == "__main__":
    # Verwendung: python3 automate_escape_room_laptop.py <open/close> <filetype> <room> <filename>
    # open/close
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "TXT", "Multimedia", "EingabeMorsecode"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "TXT", "Multimedia", "EingabeMorsecode"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "TXT", "Multimedia", "EingabeNumbleLoesung"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "TXT", "Multimedia", "EingabeNumbleLoesung"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "ZIP", "Multimedia", "TagebucheintragReise"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "ZIP", "Multimedia", "TagebucheintragReise"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "ZIP", "Multimedia", "TagebuchMorsecode"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "ZIP", "Multimedia", "TagebuchMorsecode"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "ZIP", "Multimedia", "Weltuhr"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "ZIP", "Multimedia", "Weltuhr"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "TXT", "IoT", "HinweisAufgabeMordtat"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "TXT", "IoT", "HinweisAufgabeMordtat"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "TXT", "IoT", "EingabeMordtat"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "TXT", "IoT", "EingabeMordtat"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "TXT", "IoT", "EingabeSchaedel"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "TXT", "IoT", "EingabeSchaedel"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "HTML", "IoT", "ErkennungPosen"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "HTML", "IoT", "ErkennungPosen"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "HTML", "IoT", "ErkennungTotenschaedel"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "HTML", "IoT", "ErkennungTotenschaedel"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "ZIP", "Bad", "Abschlussquiz"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "ZIP", "Bad", "Abschlussquiz"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "open", "PNG", "Bad", "Zeitungsartikel"])
    time.sleep(5)
    subprocess.Popen(['python3', BASE_PATH + "automate_escape_room_laptop.py", "close", "PNG", "Bad", "Zeitungsartikel"])
